# Generated by Django 4.2.3 on 2023-08-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='is_auction',
            field=models.BooleanField(help_text='отметьте, если торг по объявлению уместен', verbose_name='уместен ли торг'),
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
